// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DynamoDBv2.Transactions.SourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public sealed class DynamoDbMappingGenerator : IIncrementalGenerator
    {
        private const string DynamoDbGenerateMappingAttr = "DynamoDbGenerateMappingAttribute";
        private const string DynamoDbGenerateMappingFullName = "DynamoDBv2.Transactions.DynamoDbGenerateMappingAttribute";
        private const string DynamoDBHashKeyAttr = "DynamoDBHashKeyAttribute";
        private const string DynamoDBRangeKeyAttr = "DynamoDBRangeKeyAttribute";
        private const string DynamoDBPropertyAttr = "DynamoDBPropertyAttribute";
        private const string DynamoDBVersionAttr = "DynamoDBVersionAttribute";
        private const string DynamoDBTableAttr = "DynamoDBTableAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Pipeline 1: classes with [DynamoDbGenerateMapping]
            var byAttribute = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    DynamoDbGenerateMappingFullName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, ct) => GetTypeModel(ctx.TargetSymbol as INamedTypeSymbol))
                .Where(static m => m is not null)
                .Select(static (m, _) => m!);

            // Pipeline 2: partial classes that have any property with [DynamoDBHashKey]
            var byHashKey = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.Modifiers.Any(SyntaxKind.PartialKeyword) &&
                        cds.Members.OfType<PropertyDeclarationSyntax>()
                            .Any(p => p.AttributeLists
                                .SelectMany(al => al.Attributes)
                                .Any(a =>
                                {
                                    var name = a.Name.ToString();
                                    return name == "DynamoDBHashKey" || name == "DynamoDBHashKeyAttribute"
                                        || name == "Amazon.DynamoDBv2.DataModel.DynamoDBHashKey"
                                        || name == "Amazon.DynamoDBv2.DataModel.DynamoDBHashKeyAttribute";
                                })),
                    transform: static (ctx, ct) =>
                    {
                        var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) as INamedTypeSymbol;
                        return GetTypeModel(symbol);
                    })
                .Where(static m => m is not null)
                .Select(static (m, _) => m!);

            // Combine both pipelines, deduplicate by fully qualified name
            var allTypes = byAttribute.Collect()
                .Combine(byHashKey.Collect())
                .SelectMany(static (pair, _) =>
                {
                    var dict = new Dictionary<string, TypeModel>();
                    foreach (var m in pair.Left)
                    {
                        dict[m.FullyQualifiedName] = m;
                    }
                    foreach (var m in pair.Right)
                    {
                        if (!dict.ContainsKey(m.FullyQualifiedName))
                        {
                            dict[m.FullyQualifiedName] = m;
                        }
                    }
                    return dict.Values.ToImmutableArray();
                })
                .Collect();

            context.RegisterSourceOutput(allTypes, static (spc, types) =>
            {
                foreach (var type in types)
                {
                    var source = GeneratePartialClass(type);
                    var hintName = type.FullyQualifiedName.Replace("global::", "").Replace("::", ".");
                    spc.AddSource($"{hintName}.DynamoDbMapping.g.cs", source);
                }

                if (types.Length > 0)
                {
                    var registration = GenerateRegistration(types);
                    spc.AddSource("DynamoDbMappingRegistration.g.cs", registration);
                }
            });
        }

        private static TypeModel? GetTypeModel(INamedTypeSymbol? symbol)
        {
            if (symbol is null)
            {
                return null;
            }

            var tableName = symbol.Name;
            var tableAttr = symbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == DynamoDBTableAttr);
            if (tableAttr is not null && tableAttr.ConstructorArguments.Length > 0)
            {
                var arg = tableAttr.ConstructorArguments[0];
                if (arg.Value is string s && !string.IsNullOrWhiteSpace(s))
                {
                    tableName = s;
                }
            }

            var ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? ""
                : symbol.ContainingNamespace.ToDisplayString();

            var properties = new List<PropertyModel>();
            string? hashKeyAttributeName = null;
            string? versionPropertyName = null;
            string? versionPropertyType = null;
            bool versionIsNullable = false;

            foreach (var member in symbol.GetMembers())
            {
                if (member is not IPropertySymbol prop)
                {
                    continue;
                }

                if (prop.DeclaredAccessibility != Accessibility.Public)
                {
                    continue;
                }

                if (prop.GetMethod is null)
                {
                    continue;
                }

                var attrName = prop.Name;
                bool isHashKey = false;
                bool isRangeKey = false;
                bool isVersion = false;

                foreach (var attr in prop.GetAttributes())
                {
                    var className = attr.AttributeClass?.Name;

                    if (className == DynamoDBHashKeyAttr)
                    {
                        isHashKey = true;
                        var customName = GetAttributeNameArg(attr);
                        if (customName != null)
                        {
                            attrName = customName;
                        }

                        hashKeyAttributeName = attrName;
                    }
                    else if (className == DynamoDBRangeKeyAttr)
                    {
                        isRangeKey = true;
                        var customName = GetAttributeNameArg(attr);
                        if (customName != null)
                        {
                            attrName = customName;
                        }
                    }
                    else if (className == DynamoDBPropertyAttr)
                    {
                        var customName = GetAttributeNameArg(attr);
                        if (customName != null)
                        {
                            attrName = customName;
                        }
                    }
                    else if (className == DynamoDBVersionAttr)
                    {
                        isVersion = true;
                        versionPropertyName = prop.Name;
                        versionPropertyType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        versionIsNullable = prop.Type.NullableAnnotation == NullableAnnotation.Annotated
                            || (prop.Type is INamedTypeSymbol nts && nts.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T);
                    }
                }

                properties.Add(new PropertyModel
                {
                    Name = prop.Name,
                    AttributeName = attrName,
                    TypeFullName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    IsHashKey = isHashKey,
                    IsRangeKey = isRangeKey,
                    IsVersion = isVersion,
                    IsNullableValueType = prop.Type is INamedTypeSymbol nt
                        && nt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T,
                    IsReferenceType = prop.Type.IsReferenceType,
                    NullableAnnotation = prop.Type.NullableAnnotation
                });
            }

            return new TypeModel
            {
                Name = symbol.Name,
                Namespace = ns,
                FullyQualifiedName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                TableName = tableName,
                HashKeyAttributeName = hashKeyAttributeName ?? symbol.Name,
                Properties = properties,
                VersionPropertyName = versionPropertyName,
                VersionPropertyType = versionPropertyType,
                VersionIsNullable = versionIsNullable
            };
        }

        private static string? GetAttributeNameArg(AttributeData attr)
        {
            // Check constructor arguments first (positional)
            if (attr.ConstructorArguments.Length > 0)
            {
                var arg = attr.ConstructorArguments[0];
                if (arg.Value is string s && !string.IsNullOrWhiteSpace(s))
                {
                    return s;
                }
            }

            // Check named arguments (AttributeName = "...")
            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "AttributeName" && named.Value.Value is string s && !string.IsNullOrWhiteSpace(s))
                {
                    return s;
                }
            }

            return null;
        }

        private static string GeneratePartialClass(TypeModel type)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Amazon.DynamoDBv2;");
            sb.AppendLine("using Amazon.DynamoDBv2.Model;");
            sb.AppendLine("using DynamoDBv2.Transactions;");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(type.Namespace);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {type.Namespace}");
                sb.AppendLine("{");
            }

            var indent = hasNamespace ? "    " : "";

            sb.AppendLine($"{indent}partial class {type.Name}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public static class __DynamoDbMetadata");
            sb.AppendLine($"{indent}    {{");

            // TableName
            sb.AppendLine($"{indent}        public const string TableName = \"{EscapeString(type.TableName)}\";");
            sb.AppendLine();

            // HashKeyAttributeName
            sb.AppendLine($"{indent}        public const string HashKeyAttributeName = \"{EscapeString(type.HashKeyAttributeName)}\";");
            sb.AppendLine();

            // GetPropertyAttributeName
            sb.AppendLine($"{indent}        public static string GetPropertyAttributeName(string propertyName)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            return propertyName switch");
            sb.AppendLine($"{indent}            {{");
            foreach (var prop in type.Properties)
            {
                sb.AppendLine($"{indent}                \"{prop.Name}\" => \"{EscapeString(prop.AttributeName)}\",");
            }
            sb.AppendLine($"{indent}                _ => throw new ArgumentException($\"Property {{propertyName}} not found on type {EscapeString(type.Name)}\"),");
            sb.AppendLine($"{indent}            }};");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine();

            // MapToAttributes
            sb.AppendLine($"{indent}        public static Dictionary<string, AttributeValue> MapToAttributes({type.Name} obj)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            if (obj == null) return new Dictionary<string, AttributeValue>();");
            sb.AppendLine($"{indent}            var attributeMap = new Dictionary<string, AttributeValue>({type.Properties.Count});");
            sb.AppendLine();

            foreach (var prop in type.Properties)
            {
                if (prop.IsVersion)
                {
                    // Version property: replicate DynamoDbMapper.MapToAttribute version logic
                    sb.AppendLine($"{indent}            // Version property");
                    sb.AppendLine($"{indent}            {{");
                    sb.AppendLine($"{indent}                var versionValue = obj.{prop.Name};");

                    if (prop.IsNullableValueType)
                    {
                        // Nullable numeric type
                        sb.AppendLine($"{indent}                if (versionValue != null && (versionValue is int || versionValue is long || versionValue is decimal))");
                        sb.AppendLine($"{indent}                {{");
                        sb.AppendLine($"{indent}                    attributeMap[\"{EscapeString(prop.AttributeName)}\"] = new AttributeValue {{ N = versionValue.ToString() }};");
                        sb.AppendLine($"{indent}                }}");
                        sb.AppendLine($"{indent}                else if (versionValue == null)");
                        sb.AppendLine($"{indent}                {{");
                        sb.AppendLine($"{indent}                    attributeMap[\"{EscapeString(prop.AttributeName)}\"] = new AttributeValue {{ NULL = true }};");
                        sb.AppendLine($"{indent}                }}");
                    }
                    else
                    {
                        // Non-nullable numeric type (int, long, decimal)
                        sb.AppendLine($"{indent}                attributeMap[\"{EscapeString(prop.AttributeName)}\"] = new AttributeValue {{ N = versionValue.ToString() }};");
                    }

                    sb.AppendLine($"{indent}            }}");
                }
                else
                {
                    // Normal property — emit type-specific inline code when possible
                    var inlineExpr = GetInlineAttributeValueExpression(prop, "obj");

                    if (inlineExpr != null)
                    {
                        // Known type: emit direct AttributeValue construction (no virtual dispatch)
                        if (prop.IsReferenceType || prop.NullableAnnotation == NullableAnnotation.Annotated || prop.IsNullableValueType)
                        {
                            sb.AppendLine($"{indent}            if (obj.{prop.Name} != null)");
                            sb.AppendLine($"{indent}                attributeMap[\"{EscapeString(prop.AttributeName)}\"] = {inlineExpr};");
                        }
                        else
                        {
                            // Value type, always non-null — no checks needed
                            sb.AppendLine($"{indent}            attributeMap[\"{EscapeString(prop.AttributeName)}\"] = {inlineExpr};");
                        }
                    }
                    else if (prop.IsReferenceType || prop.NullableAnnotation == NullableAnnotation.Annotated || prop.IsNullableValueType)
                    {
                        // Unknown nullable type: fall back to DynamoDbMapper.GetAttributeValue
                        sb.AppendLine($"{indent}            if (obj.{prop.Name} != null)");
                        sb.AppendLine($"{indent}            {{");
                        sb.AppendLine($"{indent}                var __attrVal = DynamoDbMapper.GetAttributeValue(obj.{prop.Name});");
                        sb.AppendLine($"{indent}                if (__attrVal != null)");
                        sb.AppendLine($"{indent}                    attributeMap[\"{EscapeString(prop.AttributeName)}\"] = __attrVal;");
                        sb.AppendLine($"{indent}            }}");
                    }
                    else
                    {
                        // Unknown non-null value type: fall back
                        sb.AppendLine($"{indent}            {{");
                        sb.AppendLine($"{indent}                var __attrVal = DynamoDbMapper.GetAttributeValue(obj.{prop.Name});");
                        sb.AppendLine($"{indent}                if (__attrVal != null)");
                        sb.AppendLine($"{indent}                    attributeMap[\"{EscapeString(prop.AttributeName)}\"] = __attrVal;");
                        sb.AppendLine($"{indent}            }}");
                    }
                }
            }

            sb.AppendLine();
            sb.AppendLine($"{indent}            return attributeMap;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine();

            // GetVersion
            sb.AppendLine($"{indent}        public static (string? VersionProperty, object? Value) GetVersion({type.Name} item)");
            sb.AppendLine($"{indent}        {{");
            if (type.VersionPropertyName != null)
            {
                sb.AppendLine($"{indent}            if (item == null) return (null, null);");
                sb.AppendLine($"{indent}            return (\"{EscapeString(type.VersionPropertyName)}\", item.{type.VersionPropertyName});");
            }
            else
            {
                sb.AppendLine($"{indent}            return (null, null);");
            }
            sb.AppendLine($"{indent}        }}");

            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string GenerateRegistration(ImmutableArray<TypeModel> types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using DynamoDBv2.Transactions;");
            sb.AppendLine();

            // Import namespaces for the types
            var namespaces = types
                .Where(t => !string.IsNullOrEmpty(t.Namespace))
                .Select(t => t.Namespace)
                .Distinct()
                .OrderBy(n => n);
            foreach (var ns in namespaces)
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine();

            sb.AppendLine("namespace DynamoDBv2.Transactions.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class DynamoDbMappingRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        internal static void Register()");
            sb.AppendLine("        {");

            foreach (var type in types)
            {
                var typeName = string.IsNullOrEmpty(type.Namespace)
                    ? type.Name
                    : $"{type.Namespace}.{type.Name}";

                sb.AppendLine($"            DynamoDbMapper.RegisterGeneratedMapping<{typeName}>(");
                sb.AppendLine($"                new GeneratedTypeMapping<{typeName}>(");
                sb.AppendLine($"                    {typeName}.__DynamoDbMetadata.TableName,");
                sb.AppendLine($"                    {typeName}.__DynamoDbMetadata.HashKeyAttributeName,");
                sb.AppendLine($"                    {typeName}.__DynamoDbMetadata.GetPropertyAttributeName,");
                sb.AppendLine($"                    obj => {typeName}.__DynamoDbMetadata.MapToAttributes(obj),");
                sb.AppendLine($"                    item => {typeName}.__DynamoDbMetadata.GetVersion(item)));");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Returns an inline C# expression that constructs an AttributeValue directly
        /// for known primitive types, or null if the type needs the generic fallback.
        /// </summary>
        private static string? GetInlineAttributeValueExpression(PropertyModel prop, string objVar)
        {
            // Strip "global::" prefix and Nullable wrapper for matching
            var typeName = prop.TypeFullName;
            var isNullable = prop.IsNullableValueType;
            var innerType = typeName;

            // Handle Nullable<T>: "global::System.DateTime?" → "global::System.DateTime"
            // or "global::System.Nullable<global::System.Int64>" → "global::System.Int64"
            if (isNullable)
            {
                if (innerType.EndsWith("?"))
                {
                    innerType = innerType.Substring(0, innerType.Length - 1);
                }
                else if (innerType.Contains("System.Nullable<"))
                {
                    var start = innerType.IndexOf('<') + 1;
                    var end = innerType.LastIndexOf('>');
                    if (start > 0 && end > start)
                    {
                        innerType = innerType.Substring(start, end - start);
                    }
                }
            }

            // Normalize: strip "global::" prefix
            innerType = innerType.Replace("global::", "");
            var access = $"{objVar}.{prop.Name}";

            // For nullable value types, use .Value to unwrap
            var valueAccess = isNullable ? $"{access}.Value" : access;

            return innerType switch
            {
                "System.String" or "string" =>
                    $"new AttributeValue {{ S = {access} }}",
                "System.Int32" or "int" =>
                    $"new AttributeValue {{ N = {valueAccess}.ToString(System.Globalization.CultureInfo.InvariantCulture) }}",
                "System.Int64" or "long" =>
                    $"new AttributeValue {{ N = {valueAccess}.ToString(System.Globalization.CultureInfo.InvariantCulture) }}",
                "System.Decimal" or "decimal" =>
                    $"new AttributeValue {{ N = {valueAccess}.ToString(System.Globalization.CultureInfo.InvariantCulture) }}",
                "System.Double" or "double" =>
                    $"new AttributeValue {{ N = {valueAccess}.ToString(System.Globalization.CultureInfo.InvariantCulture) }}",
                "System.Single" or "float" =>
                    $"new AttributeValue {{ N = {valueAccess}.ToString(System.Globalization.CultureInfo.InvariantCulture) }}",
                "System.Boolean" or "bool" =>
                    $"new AttributeValue {{ BOOL = {valueAccess} }}",
                "System.DateTime" =>
                    $"new AttributeValue {{ S = {valueAccess}.ToUniversalTime().ToString(\"yyyy-MM-ddTHH:mm:ss.fffZ\") }}",
                "System.Guid" =>
                    $"new AttributeValue {{ S = {valueAccess}.ToString() }}",
                _ => null
            };
        }

        private static string EscapeString(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
        }

        private sealed class TypeModel
        {
            public string Name { get; set; } = "";
            public string Namespace { get; set; } = "";
            public string FullyQualifiedName { get; set; } = "";
            public string TableName { get; set; } = "";
            public string HashKeyAttributeName { get; set; } = "";
            public List<PropertyModel> Properties { get; set; } = new List<PropertyModel>();
            public string? VersionPropertyName { get; set; }
            public string? VersionPropertyType { get; set; }
            public bool VersionIsNullable { get; set; }
        }

        private sealed class PropertyModel
        {
            public string Name { get; set; } = "";
            public string AttributeName { get; set; } = "";
            public string TypeFullName { get; set; } = "";
            public bool IsHashKey { get; set; }
            public bool IsRangeKey { get; set; }
            public bool IsVersion { get; set; }
            public bool IsNullableValueType { get; set; }
            public bool IsReferenceType { get; set; }
            public NullableAnnotation NullableAnnotation { get; set; }
        }
    }
}
